jasypt:
  encryptor:
    bean: stringEncryptor

--- # local
spring:
  profiles: local
  data:
    mongodb:
      host: ENC(MBY9rwdupIyGBSjyVCKoJ6Iof6pEFS+ohMawL4HONZtN8bnU2v487BvmqGKaa/ds) # format of text to need to decrypt
      port: ENC(3QAKffLGMBEyXrtaDNGElruN1bep4JUtxL5ILtQ5lQ4=)
      database: ENC(hiR/BQdgYXx0t5new+iykrOTti/rAlajb5UFAoQnm1Y=)
      username: ENC(hiR/BQdgYXx0t5new+iykrOTti/rAlajb5UFAoQnm1Y=)
      password: ENC(X3Fdb3SPDusQjJUQ6UI2K6VPW24yRO7cxDV2cWSi16s=)
logging:
  level:
    root: debug

--- # dev
spring:
  profiles: dev
  data:
    mongodb:
      host: ENC(MBY9rwdupIyGBSjyVCKoJ6Iof6pEFS+ohMawL4HONZtN8bnU2v487BvmqGKaa/ds) # format of text to need to decrypt
      port: ENC(3QAKffLGMBEyXrtaDNGElruN1bep4JUtxL5ILtQ5lQ4=)
      database: ENC(hiR/BQdgYXx0t5new+iykrOTti/rAlajb5UFAoQnm1Y=)
      username: ENC(hiR/BQdgYXx0t5new+iykrOTti/rAlajb5UFAoQnm1Y=)
      password: ENC(X3Fdb3SPDusQjJUQ6UI2K6VPW24yRO7cxDV2cWSi16s=)
server:
  port: 8899
logging:
  level:
    root: info

--- # prod
spring:
  profiles: prod
server:
  port: 80
logging:
  level:
    root: error
